### PR TITLE
initial plumbing of refresh configuration

### PR DESCRIPTION
**Pull request by chrisndodge**

### CODE REVIEW

**Comment by asadiqbal08** [comment]
@chrisndodge please look into the change set that is related to SOL-439 and let me know if anything else required in it. currently i am just committing a .mp3 file for testing. we can add some other sounds as well. 

- note: 
currently, i am not rebasing this branch with 'muhhshoaib/SOL-SOL-346-Notification-list-pane' as @muhhshoaib is fixing some rebasing issues.

**Comment by chrisndodge** [comment]
@asadiqbal08 since it appears that the merge conflicts got fixed on Shoaib's branch, can you rebase this? Thanks.

**Comment by chrisndodge** [comment]
@asadiqbal08 tried this out. Seems to work. That notification audio tone is pretty funny, but I'll look around for other possibilities. At some point we might to have multiple tones and have the backbone initialization scripts say which one to use. But let's save that for another day.

Once you rebase this against muhhshoaib/SOL-SOL-346-Notification-list-pane I'll merge it in.

**Comment by chrisndodge** [comment]
@asadiqbal08 closing this. Due to some merge conflicts, I created a new branch and cherry picked these commits: https://github.com/edx/edx-notifications/pull/31

**Comment by asadiqbal08** [comment]
@chrisndodge yes tone is not ideal as it is just for demonstration.

**Pull request closed without merging**
