### PR TITLE
Kashif/minor cahnges in tests

### PR DESCRIPTION
**Pull request by kashifch**
Added engagement leaderboard notification in bok-choy
added some jasmine tests

### CODE REVIEW

**Comment by kashifch** [comment]
added support for PhantomJS2 as tests which included prototypes or bindings were failing on PhantomJS older version

**Comment by kashifch** [comment]
Hi @chrisndodge ,
In the last commit I have changed something from notification_pane_view.js file, the .xns-hide_pane was written as .xns-hide_pane in it due to which the click event on hide button was not working, As by default we have the hide link settings turned to false so bok-choy test was skipped, I have turned the setting as true in bok-choy test settings so the test will now run every time. Overall it seems to be working fine but do take a look to verify that this change does not break anything else

**Comment by kashifch** [comment]
seems like we have another flaky test, will look into it tonight

**Comment by kashifch** [comment]
added a couple of waits for flakiness, let's see if these work

**Comment by chrisndodge** [comment]
@kashifch thanks for catching the hide-pane bad class name.

**Pull request merged**
