### PR TITLE
Do not allow Python 3.5 test failures

### PR DESCRIPTION
**Pull request by moeez96**
Remove allow_failures for python 3.5 from travis configuration.

### CODE REVIEW

**Comment by moeez96** [comment]
@ihtram Please review

**Comment by msaqib52** [comment]
@ihtram could you create a release tag for python 3 changes, so we can use it.

**Comment by ihtram** [comment]
@msaqib52  Created a new release tag 1.0 with name "Added python3 support"

**Comment by edx-webhook** [comment]
Although this pull request is already merged, I've created [OSPR-5416](https://openedx.atlassian.net/browse/OSPR-5416) so that we can track it in Jira.

There is nothing you have to do. No action is needed from your side.  Thanks again for your contribution.

**Pull request merged**
