### PR TITLE
[MCKIN-11138] Add Polish translations

### PR DESCRIPTION
**Pull request by xitij2000**
This PR adds Polish translations and Polish language support to edx-notificaitons. 

**Merge deadline**: ASAP

**Reviewers**
- [ ] @xirdneh 
- [ ] edX reviewer[s] TBD

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @xitij2000! I've created [OSPR-3676](https://openedx.atlassian.net/browse/OSPR-3676) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by xitij2000** [comment]
@smagoun Hi! This PR is read for review.

**Comment by smagoun** [comment]
Looks like the metadata in each PO file is incomplete. I'd prefer to have those fixed, though it looks like we have missing / incorrect metadata in the other PO files too.

**Comment by xitij2000** [comment]
@smagoun OK, will look into this.

**Comment by xitij2000** [comment]
@ihtram I don't have access to this data, I'll try to ping again about this. I don't see metadata in the other files either so don't know if there is standard bit of metadata that can be used here.

**Comment by edx-webhook** [comment]
Thanks for the pull request, @xitij2000! I've created [OSPR-5445](https://openedx.atlassian.net/browse/OSPR-5445) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@xitij2000 Sorry for the long wait, our bot only processed this now. Are you still interested in this PR?

**Comment by xitij2000** [comment]
@natabene I unfortunately still don't have the required data here. I'll try and rebase the PR and see how it fares currently.

**Comment by natabene** [comment]
@xitij2000 Excellent, thank you.

**Comment by natabene** [comment]
@shafqatfarhan Please review this once author implements feedback.

**Comment by edx-webhook** [comment]
@xitij2000 Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-notifications&entry.867055334=https://github.com/edx/edx-notifications/pull/195&entry.1484655318=https://github.com/xitij2000&entry.752974735=2019-06-18+12:47&entry.1917517419=2021-03-12+09:53&entry.2133058324=No) so we can improve your experience in the future.

**Comment by xitij2000** [comment]
It seems these translations were already added.

**Pull request closed without merging**
