### PR TITLE
Provide for arbitrary groupings of presenting notifications plus do some...

### PR DESCRIPTION
**Pull request by chrisndodge**
... McKA confirming to the PDF

### CODE REVIEW

**Comment by chrisndodge** [comment]
@afzaledx @muhhshoaib FYI, this isn't going to merge until after the demo.

**Comment by kashifch** [comment]
hmm, the test fails due to change in sort order, I was picking the notification on the top, I think I would need to look for groups groups in the test

**Comment by chrisndodge** [comment]
Seems like the new groups/ordering is breaking a bok choy test because it expects some particular content to be at the top. I'll fix the test tomorrow.

**Comment by kashifch** [comment]
sorry for the intrusion but since I figured out the solution I am taking the liberty to update the tests. I will upadate my branch with same changes as well to avoid any conflicts

**Pull request merged**
