### PR TITLE
MCKIN-27715: add missing translations

### PR DESCRIPTION
**Pull request by msaqib52**
@shafqatfarhan This PR adds some missing translations, could you please review it.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @msaqib52! I've created [OSPR-5276](https://openedx.atlassian.net/browse/OSPR-5276) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by natabene** [comment]
@msaqib52 Thank you for your contribution. Please let me know once it is ready for our review. @shafqatfarhan our team are owners of this repo, please review and merge once they are ready.

**Review by hasnain-naveed — APPROVED** [review]
looks good to me.

**Comment by edx-webhook** [comment]
@msaqib52 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-notifications&entry.867055334=https://github.com/edx/edx-notifications/pull/232&entry.1484655318=https://github.com/msaqib52&entry.752974735=2020-12-02+12:30&entry.1917517419=2020-12-04+12:57&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
