### PR TITLE
Revert "Add API to purge notifications for specific users"

### PR DESCRIPTION
**Pull request by ormsbee**
Reverts edx/edx-notifications#190

The original PR needs to be rebased and then the version set correctly (the version has advanced past 1.0 in the time between when the original PR was opened and merged). Sorry I didn't catch this earlier.

### CODE REVIEW

**Comment by nasirhjafri** [comment]
Version 0.9.0 is being used in `edx-solutions` fork. Can we please keep release tag `0.9.0`. Thanks!

**Comment by ormsbee** [comment]
@nasirhjafri: I'm still confused about the versioning here, but I don't really care what the version is as long as it makes some kind of sense to the respective teams.

This is my understanding (please correct me where I'm wrong, because I'm pretty sure I'm wrong on at least some of these):

1. We have two active branches for this project: `development` and `master`.
2. They've diverged somewhat, since `master` is at 1.0.2 and `development` is at 0.9.0.
3. The `edx-solutions` fork is running off of `development`.
4. The `master` branch is being used by community members in general.
5. The `development` branch exists because it needs to support Django 1.8, where `master` assumes Django 1.11.

My questions:

A) Was it appropriate for #190 to have been a PR against `development`? Should it have gone against `master` instead?
B) If we leave it in the `development` branch (now that things have been merged), what would be the timeline for merging `development` back into master?

Thank you.

**Comment by ormsbee** [comment]
If the answer to (A) is that it was the intended merge target, then please feel free to close this revert PR.

**Comment by natabene** [comment]
@ihtram Anything you can add here?

**Comment by ihtram** [comment]
@ormsbee Your understandings are perfect and all the above 5 points are valid.so 
 (A) PR #190 was supposed to merge into development as it was related to edx-platform and for platform we are using development branch.
(B) We are rebasing ironwood release and once we are done with this rebase we will merge development into master. As ironwood supports Django 1.11 so after rebase to ironwood there will be no need of Django 1.8  So with ironwood, we will be using master for both platform and apors(a community member)
@natabene

**Pull request closed without merging**
