### PR TITLE
[MCKIN-9477] - Cleared interval for autoRefreshNotifications when session expires

### PR DESCRIPTION
**Pull request by nasirhjafri**
MCKIN-9477

Cleared interval for autoRefreshNotifications when session expires

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @nasirhjafri! I've created [OSPR-3021](https://openedx.atlassian.net/browse/OSPR-3021) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@nasirhjafri Hi, was this PR actually intended for Solutions fork? If not, and please provide more information about what this achieves, so we can review it. Also, if you want to contribute this code to edx/edx-notifications repo, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions to repos in edx Github org. Thanks.

**Comment by nasirhjafri** [comment]
Hi @natabene yes actually it was intended for Solutions fork. I've already sent a signed Contributor Agreement.

**Comment by natabene** [comment]
@nasirhjafri Sorry, still confused: This repo is for the open edx notifications. Did you intend your PR to be for edx-solutions/cs_comments_service.git or edx-solutions/edx-platform. ? Or did you already make a change there and now are upstreaming your change from solutions fork to the Open edX repo?

**Comment by nasirhjafri** [comment]
Hi @natabene This PR is intended for apros. Unfortunately, they are still using `edx/edx-notifications` for notifications instead of any forked repo. I'll ask for a forked repo and create a PR there. Thanks!

**Comment by natabene** [comment]
@nasirhjafri Thank your explanation and your patience. @ihtram  Can you review this?

**Comment by edx-webhook** [comment]
@nasirhjafri 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-notifications&entry.867055334=https://github.com/edx/edx-notifications/pull/189&entry.1484655318=https://github.com/nasirhjafri&entry.752974735=2019-01-29+11:18&entry.1917517419=2019-02-15+11:19&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
